### ISSUE TITLE
token instead of UUID

### ISSUE THREAD

**Issue by ericsullivan** [riebeekn/phx_gen_auth_with_registration_tokens#1]
Thanks for the article:
https://experimentingwithcode.com/restricting-registrations-when-using-phx-gen-auth-part-1/

I used it as the basis for a similar system. One change I made was to use tokens instead of UUIDs.
I found an elixir forum post explaining the timing issue:
https://elixirforum.com/t/phx-gen-auth-why-does-hashing-the-tokens-prevent-timing-attacks/33927/3

That change basically makes them work like the confirmation tokens.

**Comment by riebeekn** [comment]
Thanks for logging this, timing attacks never occurred to me when I was thinking about the registration token, but it's a very good point!  When I get some time I'll update the code and the blog post... glad you found the article useful.

**Comment by riebeekn** [comment]
Thanks again for pointing this out, much appreciated!
